name: workflow2
on: workflow_dispatch

jobs:
  job-1:
     runs-on: ubuntu-24.04
     steps:
       - name: print era idiot
         run: echo "idoit"
       - name: print cpu infro
         run: lscpu
       - name: print mem info
         run: lsmem
